baseURL                 = "https://owlinux1000.github.io"
title                   = "$ make life"
# for smart copyright line, leave this blank and check [params.copyright]
copyright               = ""

theme                   = "minimo"

disqusShortname         = "alicemacs"
googleAnalytics         = "UA-154126244-1"

Paginate                = 5
preserveTaxonomyNames   = true

enableRobotsTXT         = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences      = true

enableEmoji             = true

# Missing translations will default to this content language
defaultContentLanguage  = "en"

publishDir              = "docs/"

[params.info]
description             = "Making the world more secure"
title404                = "Nothing's here!"

[params.assets]
favicon                 = "favicon.ico"
customCSS               = ["css/custom.css"]
customJS                = ["js/custom.js"]
gopher                  = "" # used in 404 template ( Generator:https://gopherize.me )

[params.copyright]
prefix                  = ""
holder                  = "Chihiro Hasegawa"
startYear               = "2021"
suffix                  = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat              = "2006, Jan 02"
listDateFormat          = "2006, Jan 02"
archiveDateFormat       = "Jan 02"
hideEntryNavigation     = ["page"] # boolean / array of sections
hideEntryMeta           = ["page"] # boolean / array of sections
showReadingTime         = true
showLastmod             = true
accentColor             = "#ffcd00"
hideMainMenu            = false

[params.sidebar]
enable                  = true

[params.widgets]
homepage                = ["recent_posts"]
sidebar                 = ["about","sidebar_menu"]
footer                  = ["social_menu"]

[params.opengraph.twitter]
page                    = "encry1024" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator          = ""

[params.social]
email                   = "encry1024@gmail.com"
facebook                = "MunifTanjim"
github                  = "owlinux1000"
instagram               = "encry1024"
twitter                 = "encry1024"

[params.comments]
enable                  = false

[permalinks]
page                    = "/:slug/"

[[menu.main]]
name                    = "Résumé"
weight                  = 1
identifier              = "resume"
url                     = "/resume/"

[[menu.main]]
name                    = "Blog"
weight                  = 2
identifier              = "blog"
url                     = "/blog/"

[[menu.main]]
name                    = "Private"
weight                  = 3
identifier              = "private"
url                     = "/private/"

[blackfriday]
hrefTargetBlank         = true

[languages]
# edit this block for your own language
[languages.en]
lang                    = "en"
languageName            = "English"
weight                  = 1